POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "este é o primeiro video",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

GET http://localhost:3333/videoById/50b05686-e39d-4865-8cc9-547bf9e9109d
###

PUT http://localhost:3333/videos/d17d052e-024f-45bb-b213-6845d701fdf1
Content-Type: application/json

{
    "title": "mudando title do video 03",
    "description": "editando video 03",
    "duration": 190
}

###

DELETE http://localhost:3333/videos/411d5c15-7ecf-4403-8872-a0de3fff77f2